# --- Configuración de SQL Server ---
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Empresa;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Anghelo123*
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- Configuración JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto de la aplicación
server.port=8081